create table employee(
employee_id varchar2(250) not null,
employee_name varchar2(250) not null,
employee_salary number(25,3) null,
employee_gender char(4) not null,
employee_joining_date date null,
employee_mobile varchar2(15) not null,
employee_email varchar2(30) not null,
employee_company_name varchar2(25) null,
employee_location varchar2(25) null,
employee_dept varchar2(25) null
);

--insert the employee data from dev to sit_env
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('R7890','Ram',25000.09,'M   ',to_date('31-OCT-22','DD-MON-RR'),'+9024422423','ram1@gmail.com',null,'Hyderabad','Tech Leader');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('V7780','Vikram',52000.2,'M   ',to_date('01-MAR-21','DD-MON-RR'),'+989098734','vikram11@techmahendra.com','Tech Mahendra','Chennai','HR Department');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('R1022','Ramesh',28000,'M   ',to_date('10-OCT-22','DD-MON-RR'),'+9189282233','ramesh@gmail.com','HSBC','Hyderabad','IT');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('V2444','Vikram',55000.24,'M   ',to_date('01-OCT-22','DD-MON-RR'),'+91782373349','vikram@gmail.com','HCL','Bangalore','Developer');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('U2345','Umesh',27000.1,'M   ',to_date('12-NOV-22','DD-MON-RR'),'+99876543210','umesh@hcl.com','HCL','Chennai','Cleark');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('P2345','Paramesh',37005.1,'M   ',to_date('10-JAN-20','DD-MON-RR'),'+99876543333','paramesh@hcl.com','HCL','Chennai','Admin');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('C2443','Chandra',100000.24,'M   ',to_date('15-JAN-21','DD-MON-RR'),'+917896539260','chandra@ibm.com','IBM','Chenai','Developer');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('A3454','Arun',40000.4,'M   ',to_date('10-AUG-22','DD-MON-RR'),'+918938748422','arun@gmail.com','HCL','Hyderbad',null);
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('B3424','Balu',30000.04,'M   ',to_date('01-AUG-22','DD-MON-RR'),'+9178965430283','balu@gmail.com','HSBC','Pune','Cleark');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('A3425','Anil',80000.04,'M   ',to_date('11-FEB-21','DD-MON-RR'),'+918654209872','anil@gmail.com','Infosys','Bangalore','Admin');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('J3456','Jyothis',75000.04,'M   ',to_date('03-MAR-21','DD-MON-RR'),'+918765390987','jyothis@ibm.com','IBM','Hyderabad','Cleark');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('N2454','Naresh',45000,'M   ',to_date('01-AUG-22','DD-MON-RR'),'+917890374824','naresh@gmail.com','HCL','Pune','Developer');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('A6734','Arjun',50000,'M   ',to_date('08-JAN-20','DD-MON-RR'),'+918765432190','arjun@gmail.com','TCS','Chenai','Marketing');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('V1234','Vikram',48000.9,'M   ',to_date('12-JAN-21','DD-MON-RR'),'+9024422423','ram@techmahendra.com','Tech Mahendra','Pune','IT');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('P3244','Arun',25000.09,'M   ',to_date('04-NOV-22','DD-MON-RR'),'+99876543210','p324@gmail.com','HCL','Bangalore','Developer');
Insert into EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_SALARY,EMPLOYEE_GENDER,EMPLOYEE_JOINING_DATE,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL,EMPLOYEE_COMPANY_NAME,EMPLOYEE_LOCATION,EMPLOYEE_DEPT) values ('S1234','Sravani',17050.1,'F   ',to_date('10-JAN-20','DD-MON-RR'),'+98983543333','sravani@hcl.com','HCL','Hyderabad','Admin');


select * from employee;

commit;